routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', "PagesController@homepage");

Route::get('apply', "PagesController@apply")->name('apply')->middleware('application');
Route::post('apply', "PagesController@postApply")->name('postApply')->middleware('application');
Route::get('application', "PagesController@application")->name('application')->middleware('auth');

Route::resource('applications', 'App\\ApplicationsController')->middleware('admin');

app/Models/Application.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\User;
//use App\Models\ApplicationState;

class Application extends Model
{
    protected $guarded = [];
    
    private static $state_send = 1;
    private static $state_accepted = 2;
    private static $state_refused = 3;

    public function user()
    {
        return $this->hasOne('User');
    }  

    public function application_state()
    {
        return $this->belongsTo('App\Models\ApplicationState', 'application_state_id', 'id');
    }  

    public function getByUserId($user_id) {
        return Application::where("user_id", $user_id)
                            ->with(['application_state'])
                            ->first();
    } 

    public function setAccept($id) {
        $application = Application::find($id);
        $application->application_state_id = self::$state_accepted;
        $application->save();

        return true;
    } 

    public function setRefuse($id) {
        $application = Application::find($id);
        $application->application_state_id = self::$state_refused;
        $application->save();

        return true;
    } 
}

app/Http/Controllers/Ajax/ApplicationsController.php
<?php

namespace App\Http\Controllers\Ajax;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use App\Models\Application;

class ApplicationsController extends Controller
{
    public function __construct()
    {
        // Accessible only to admins
    }
    
    public function acceptApplication(Request $request)
    {
        $id = $request->get('id');
        $application = new Application();
        $application->setAccept($id);

        $this->_sendNotification($id);

        return response()->json(true);
    }  
    
    public function refuseApplication(Request $request)
    {
        $id = $request->get('id');
        $application = new Application();
        $application->setRefuse($id);

        $this->_sendNotification($id);

        return response()->json(true);
    }    

    /*
     * Notifica al candidato quando viene accettato o rifiutato
     */
    private function _sendNotification($application_id) {
        $application = Application::find($application_id)->with(['application_state'])->first();
        $user = \App\Models\User::find($application->user_id);
        if($user!==null)
            $user->sendUpdateStateApplication($user, $application);        
    }
}

app/Http/Controllers/App/ApplicationsController.php
<?php

namespace App\Http\Controllers\App;

use App\Http\Controllers\Controller;
use App\Models\Application;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class ApplicationsController extends Controller
{

    public function __construct()
    {
        // Accessible only to admins
    }

    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    { 
        if ($request->expectsJson())
            return Application::with(['application_state'])->paginate(20);

        return view('applications.index');
    }

    /**
     * @param Application $application
     */
    public function accept(Application $application)
    {
        $application->accept();
    } 
}

resources/views/applications/complete.blade.php
@extends('layouts.main')

@section('content')
    <div id="contact">
        <div class="section-content">
            <h1 class="section-header">Grazie per la tua candidatura  <span class="content-header wow fadeIn " data-wow-delay="0.2s" data-wow-duration="2s"> {{$application->first_name}}</span></h1>
            <h3>Riceverai presto una mail di risposta</h3>
        </div>

        <div class="contact-section">
            <div class="container">
                <a class="btn btn-default home-button submit" href="{{route('applications.create')}}">Torna alla home</a>
            </div>
        </div>
    </div>
@stop

resources/views/applications/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <div class="container">
            <h1>Elenco candidature</h1>
        </div>
    </section>
    <section>
        <div class="container">

            <applications inline-template>
                <div>
                    <table class="table table-hover">
                        <thead>
                          <tr>
                            <th>{{__("First Name")}}</th>
                            <th>{{__("Last Name")}}</th>
                            <th>{{__("Actions")}}</th>
                          </tr>
                        </thead>
                        <tbody>                        
                            <tr v-for="(application, index) in items" :key="application.id">
                                <td>@{{ application.first_name }}</td>
                                <td>@{{ application.last_name }}</td>
                                <td>
                                    <a class="btn btn-success" @click="accept(application)" v-if="application.application_state.code!='ACCEPTED'">{{__("Approve")}}</a>
                                    <a class="btn btn-danger" @click="refuse(application)" v-if="application.application_state.code!='REFUSED'">{{__("Refuse")}}</a></td>
                            </tr>
                        </tbody> 
                    </table>

                    <paginator :dataSet="dataSet" @changed="fetch"></paginator>
                </div>
            </applications>
        </div>
    </section>

@endsection